### ISSUE TITLE
FATAL: cbc_start failed: Invalid key size.

### ISSUE THREAD

**Issue by ChillerDragon** [fstd/pstd#3]
Even tho my pstd server does not survive longer than 1 day without this crash I cannot reproduce it. I tested it on fstd:devel because master still fails on peer address.

```
FATAL: cbc_start failed: Invalid key size. at /home/pstd/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Crypt/Mode/CBC.pm line 14.
```

I assume it fails in one of these two places and the key is either lass than 16 or not a multiple of 16:

https://github.com/DCIT/perl-CryptX/blob/master/src/ltc/ciphers/aes/aes.c#L131
https://github.com/DCIT/perl-CryptX/blob/master/src/ltc/ciphers/aes/aes.c#L735

It seems like more than 16 is just find but when playing around with the pstd soruce it said something about multiples of 16:

```
pstd_server.pl: 2019-12-16 12:15:25 +0100: decrypting key='aaaaaaaaaaaaaaaa' paste='xxxxxxxxxxxxxxxx$'
FATAL: cipher text length has to be multiple of 16 (1) at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/Crypt/Mode/CBC.pm line 20.
```

What does this code even do?
https://github.com/fstd/pstd/blob/2b2b8b211f96c62659ab0119c73e66615f60a23f/pstd_server.pl#L423-L424

How do I enter that branch and what kind of feature is that?

**Comment by fstd** [comment]
> ```
> FATAL: cbc_start failed: Invalid key size. at /home/pstd/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Crypt/Mode/CBC.pm line 14.
> ```
Not sure how you got this error, but yes AES requires a defined key size; for AES128 that's 128 bits aka 16 bytes.  Maybe (?) if you supply a 32 byte key you  get AES256, never tested that.

> ```
> pstd_server.pl: 2019-12-16 12:15:25 +0100: decrypting key='aaaaaaaaaaaaaaaa' paste='xxxxxxxxxxxxxxxx$'
> FATAL: cipher text length has to be multiple of 16 (1) at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/Crypt/Mode/CBC.pm line 20.
> ```
Here you're trying to *de*crypt something that doesn't look encrypted.  Ciphertexts in CBC mode are always a multiple of the block size in length.  *En*cryption of arbitrary lengths is fine, but only because internally it gets padded.

Note that we're not talking about the lengths of the key here, but about the length of the ciphertext.

> What does this code even do?
> https://github.com/fstd/pstd/blob/2b2b8b211f96c62659ab0119c73e66615f60a23f/pstd_server.pl#L423-L424
It dissects the first line of a HTTP request.  Full format of such a request is GET /<paste_id>/<key>/?<lang>

$1 becomes the paste id, $2 the (optional) encryption key, $3 the (optional) language id for syntax hilighting purposes.

> How do I enter that branch
By downloading a paste, typically via a web browser.

**Comment by ChillerDragon** [comment]
Ah I always red the regex wrong and tried : instead of / which makes no sense xxD.

Now I was able to crash the server with 3H/Jo being a valid pastes:
http://localhost:8080/3H/aaaaaaaaaaaaaaaa
http://paste.pr0.tips/Jo/aaaaaaaaaaaaaaaa

**Comment by fstd** [comment]
> Ah I always red the regex wrong and tried : instead of / which makes no sense xxD.
(?:<regexp>) is perl's syntax for a non-capturing group, i.e. like (<regexp>) but it doesn't assign whatever matched to a variable.

> Now I was able to crash the server with 3H being a valid paste:
> http://localhost:8080/3H/aaaaaaaaaaaaaaaa
Yeah good catch, however the paste 3H isn't actually encrypted, is it?  Still should probably catch this instead of crashing, I'll look into it.

**Comment by ChillerDragon** [comment]
No it is not encrypted I still don't know what the encryption is used for and how to do it. Is it documented somewhere?

**Comment by fstd** [comment]
> No it is not encrypted I still don't know what the encryption is used for and how to do it. Is it documented somewhere?
91f7b01cc89d4201ae4ab7c51cf4349ba9e97876 is the commit that added it.

Basically you use pstd.sh -c and your paste ends up being encrypted on the server.  I added it after someone downloaded the entire paste ID space, for cases where whatever is pasted is not really meant for public consumption.

**Comment by ChillerDragon** [comment]
Ah I see cool thanks! Oh btw is it possible to request a deletion somewhere in case of accidental leak of sensitive data?

**Comment by fstd** [comment]
> Ah I see cool thanks! Oh btw is it possible to request a deletion somewhere in case of accidental leak of sensitive data?
No, at least not without accidentally risking to allow people to delete pastes they don't own, as nothing is authenticated anywhere.

Emailing the admin so they/you delete the paste could work ;)

Other than that, feel free to implement something to that end, or perhaps time-limited pastes

**Comment by ChillerDragon** [comment]
Ok I turned on verbose mode and was able to log the request that caused the crash:
```
pstd_server.pl: 2019-12-16 22:07:03 +0000: DBG: 54.XXX.XXX.XXX: Processing 'POST /TP/public/index.php?s=captcha HTTP/1.1$$Host: 149.202.127.134:8080$$User-Agent: Go-http-client/1.1$$Content-Length: 84$$Connection: close$$Content-Type: application/x-www-form-urlencoded$$Accept-Encoding: gzip$$$$_method=__construct&filter[]=system&method=get&server[REQUEST_METHOD]=uname&ipconfig'
FATAL: cbc_start failed: Invalid key size. at /home/pstd/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Crypt/Mode/CBC.pm line 14.
```

Also this one cause a crash:
```
POST /users?page=&size=5 HTTP/1.1$$Host: 149.202.127.134:8080$$User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)$$Content-Length: 119$$Connection: close$$Content-Type: application/x-www-form-urlencoded$$Accept-Encoding: gzip$$$$username[#this.getClass().forName("java.lang.Runtime").getRuntime().exec("touch /tmp/su")]=&password=&repeatedPassword=
```

And yes ik looks like some1 is tryyin to haxx me xxD

**Comment by fstd** [comment]
Should be fixed now

**Comment by ChillerDragon** [comment]
Thanks a lot. I think after 3 days without crash its save to say its stable now!
